name: CI

on:
  pull_request:
    branches: ['stable/**']
    types: ['opened', 'reopened', 'synchronize']
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: self-hosted-2cpu
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.0.2

      - name: Import secrets
        uses: hashicorp/vault-action@cb841f2c86fb6d07cff94fda240828c1abc5ba43 # v2.7.3
        id: secrets
        with:
          exportEnv: false
          url: ${{ secrets.VAULT_URL }}
          role: ${{ secrets.VAULT_ROLE }}
          method: kubernetes
          secrets: |
            kv-gitlab-ci/data/github/ingress api_token ;
            kv-gitlab-ci/data/github/ingress user_secret ;
            kv-gitlab-ci/data/github/ingress user_uuid ;
            kv-gitlab-ci/data/github/shared/smoke-tests-registry-creds token_name ;
            kv-gitlab-ci/data/github/shared/smoke-tests-registry-creds token_secret ;
            kv-gitlab-ci/data/github/shared/smoke-tests-registry-creds registry_name ;

      - name: Login
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        with:
          registry: ${{ steps.secrets.outputs.registry_name }}
          username: ${{ steps.secrets.outputs.token_name }}
          password: ${{ steps.secrets.outputs.token_secret }}

      - name: Build image
        run: make build

      - name: Run tests
        env:
          USER_UUID: ${{ steps.secrets.outputs.user_uuid }}
          USER_SECRET: ${{ steps.secrets.outputs.user_secret }}
          WALLARM_API_TOKEN: ${{ steps.secrets.outputs.api_token }}
        run: make smoke-test
